config/routes.rb
Rails.application.routes.draw do
  resources :directors, :stars, :writers, :person

  resources :movies do
    resources :ratings
  end

  post 'movies/upload', as: :upload, to: 'movies#import'

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :person
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  acts_as_taggable
  acts_as_taggable_on :genres
  acts_as_tagger

  has_many :stars
  has_many :directors
  has_many :writers
  has_many :ratings
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :movie
end

app/models/star.rb
class Star < ApplicationRecord
  belongs_to :person
  belongs_to :movie
end

app/models/writer.rb
class Writer < ApplicationRecord
  belongs_to :person
  belongs_to :movie
end

app/controllers/PersonController.rb
class PersonController < ApplicationController
  def show
    @person = Person.find(params[:id])

    @star = Movie.joins(:stars).where(:stars => {:person_id => @person.id})
    @director = Movie.joins(:directors).where(:directors => {:person_id => @person.id})
    @writer = Movie.joins(:writers).where(:writers => {:person_id => @person.id})

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @people = Person.all
    @tags = ActsAsTaggableOn::Tag.all
  end

  def create
    movie_params = params[:movie].permit(:title, :description, :runtime)
    @movie = Movie.new(movie_params)
    @movie.save
    console

    @movie.genre_list.add(params["movie"]["genre_list"].reject{|g| g.empty?})
    @movie.save

    directors = params["movie"]["directors"].reject{|d| d.empty?}
    stars     = params["movie"]["stars"].reject{|s| s.empty?}
    writers   = params["movie"]["writers"].reject{|w| w.empty?}

    for d in directors
      @movie.directors.create!(person_id: d)
      @movie.save!
    end

    for s in stars
      @movie.stars.create!(person_id: s)
      @movie.save!
    end

    for w in writers
      @movie.writers.create!(person_id: w)
      @movie.save!
    end

    @movies = Movie.all
    render action: "index"
  end

  def edit
    @movie = Movie.find(params[:id])
    @people = Person.all
    @tags = ActsAsTaggableOn::Tag.all
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(params["movie"].permit(:title, :description, :runtime))

    @movie.genres.destroy_all

    @movie.genre_list.add(params["movie"]["genre_list"].reject{|g| g.empty?})
    @movie.save

    @movie.directors.destroy_all
    @movie.stars.destroy_all
    @movie.writers.destroy_all

    directors = params["movie"]["directors"].reject{|d| d.empty?}
    stars     = params["movie"]["stars"].reject{|s| s.empty?}
    writers   = params["movie"]["writers"].reject{|w| w.empty?}

    for d in directors
      @movie.directors.create!(person_id: d)
      @movie.save!
    end

    for s in stars
      @movie.stars.create!(person_id: s)
      @movie.save!
    end

    for w in writers
      @movie.writers.create!(person_id: w)
      @movie.save!
    end

    @movies = Movie.all
    render action: "index"
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    @movies = Movie.all
    render action: "index"
  end

  def import
    file = File.open(params[:file])
    data = JSON.parse(file.read)

    for m in data
      mm = Movie.new(title: m["title"], description: m["description"], runtime: m["runtime"])
      mm.save

      for s in m["stars"]
        p = Person.create!(first_name: s.split.first , last_name: s.split.last)
        mm.stars.create!(person_id: p.id)
      end

      for d in m["directors"]
        p = Person.create!(first_name: d.split.first , last_name: d.split.last)
        mm.directors.create!(person_id: p.id)
      end

      for w in m["writers"]
        p = Person.create!(first_name: w.split.first , last_name: w.split.last)
        mm.writers.create!(person_id: p.id)
      end

      for r in m["ratings"]
        mm.ratings.create(score: r)
      end

      mm.genre_list.add(m["genres"])
      mm.save!
    end

    @movies = Movie.all
    render action: "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/unit_helper.rb
module UnitHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h1><%= @movie.title %></h1>

<%= form_with model: @movie, local: true do |form| %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, required: true %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description, required: true %>
  </p>

  <p>
    <%= form.label :runtime %><br>
    <%= form.number_field :runtime, in: 1...1000, step: 1, required: true %>
  </p>

  <p>
    <%= form.label :genre_list %><br>
    <%= form.select(:genre_list, @tags, {}, { multiple: true, include_blank: false, required: true}) %>
  </p>

  <p>
    <%= form.label :stars %><br>
    <%= form.select(:stars, @people.map{|person| [person.first_name + ' ' + person.last_name, person.id]}, {}, { multiple: true, include_blank: false, required: true}) %>
  </p>

  <p>
    <%= form.label :writers %><br>
    <%= form.select(:writers, @people.map{|person| [person.first_name + ' ' + person.last_name, person.id]}, {}, { multiple: true, include_blank: false, required: true}) %>
  </p>

  <p>
    <%= form.label :directors %><br>
    <%= form.select(:directors, @people.map{|person| [person.first_name + ' ' + person.last_name, person.id]}, {}, { multiple: true, include_blank: false, required: true}) %>
  </p>

  <p>
    <%= link_to '<button class="btn btn-primary btn-sm">Cancel</button>'.html_safe, movies_path() %>
    <%= form.submit class: "btn btn-primary" %>
  </p>

<% end %>

<%= javascript_tag "$('#genre_list').select2()" %>
<%= javascript_tag "$('#movie_stars').select2()" %>
<%= javascript_tag "$('#movie_writers').select2()" %>
<%= javascript_tag "$('#movie_directors').select2()" %>

app/views/movies/index.html.erb
<h1>Movies
  <a href="<%= new_movie_path() %>" class="btn btn-sm btn-primary"><i class="fas fa-plus"></i> Add movie</a>
  <label class="btn btn-info btn-sm">
    <%= form_with(url: {action: :import}, multipart: true, id: 'form') do %>
      <i class="fas fa-file-import"></i> Upload movies
      <span style="display:none;">
        <%= file_field_tag 'file', id: "file-upload" %>
      </span>
    <% end %>
  </label>
</h1>

<div class="movie-cards">
<% for movie in @movies %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= movie.title %>
        <% for genre in movie.genre_list %>
          <span class="badge badge-info"><%= genre %></span>
        <% end %>
      </h5>
      <h6 class="card-subtitle text-muted">
        <span title="runtime">
          <i class="far fa-clock"></i> <%= movie.runtime.to_s + "'" %>
        </span>
        &nbsp;
        <span title="avg rating">
          <% if movie.ratings.empty? %>
            <i class="far fa-meh-blank"></i> -
          <% elsif movie.ratings.average(:score) < 3 %>
            <i class="far fa-tired"></i> <%= movie.ratings.average(:score) %>
          <% elsif movie.ratings.average(:score) < 5 %>
            <i class="far fa-frown"></i> <%= movie.ratings.average(:score) %>
          <% elsif movie.ratings.average(:score) < 7 %>
            <i class="far fa-smile"></i> <%= movie.ratings.average(:score) %>
          <% elsif movie.ratings.average(:score) < 9 %>
            <i class="far fa-grin"></i> <%= movie.ratings.average(:score) %>
          <% else %>
            <i class="far fa-grin-stars"></i> <%= movie.ratings.average(:score) %>
          <% end %>
        </span>
      </h6>

      <p><%= movie.description %></p>
      <p>
        <% if movie.directors.length >1 %>
          Directors:
        <% else %>
          Director:
        <% end %>
        <% for d in movie.directors %>
          <a href="<%= person_path(d.person.id) %>"><%= d.person.first_name + ' ' + d.person.last_name %></a>
        <% end %>
      </p>
      <p>
        <% if movie.writers.length >1 %>
          Writers:
        <% else %>
          Writer:
        <% end %>
        <% for w in movie.writers %>
          <a href="<%= person_path(w.person.id) %>"><%= w.person.first_name + ' ' + w.person.last_name %></a>
        <% end %>
      </p>
      <p>
        <% if movie.stars.length >1 %>
          Stars:
        <% else %>
          Star:
        <% end %>
        <% for s in movie.stars %>
          <a href="<%= person_path(s.person.id) %>"><%= s.person.first_name + ' ' + s.person.last_name %></a>
        <% end %>
      </p>
      <button type="button" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Add rating</button>
      <%= link_to '<button class="btn btn-primary btn-sm"><i class="fas fa-edit"></i> Edit movie</button>'.html_safe, edit_movie_path(movie.id) %>
      <%= link_to '<button class="btn btn-primary btn-sm"><i class="fas fa-trash"></i> Remove movie</button>'.html_safe, movie_path(movie.id), method: :delete %>

    </div>
  </div>
<% end %>

<script>
  $('#file-upload').on('change', function() {
      $('#form').submit()
  });
</script>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= form_with scope: :movie, url: movies_path, local: true do |form| %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, required: true %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description, required: true %>
  </p>

  <p>
    <%= form.label :runtime %><br>
    <%= form.number_field :runtime, in: 1...1000, step: 1, required: true %>
  </p>

  <p>
    <%= form.label :genre_list %><br>
    <%= form.select(:genre_list, @tags, {}, { multiple: true, include_blank: false, required: true}) %>
  </p>

  <p>
    <%= form.label :stars %><br>
    <%= form.select(:stars, @people.map{|person| [person.first_name + ' ' + person.last_name, person.id]}, {}, { multiple: true, include_blank: false, required: true}) %>
  </p>

  <p>
    <%= form.label :writers %><br>
    <%= form.select(:writers, @people.map{|person| [person.first_name + ' ' + person.last_name, person.id]}, {}, { multiple: true, include_blank: false, required: true}) %>
  </p>

  <p>
    <%= form.label :directors %><br>
    <%= form.select(:directors, @people.map{|person| [person.first_name + ' ' + person.last_name, person.id]}, {}, { multiple: true, include_blank: false, required: true}) %>
  </p>

  <p>
    <%= link_to '<button class="btn btn-primary btn-sm">Cancel</button>'.html_safe, movies_path() %>
    <%= form.submit class: "btn btn-primary" %>
  </p>

<% end %>

<%= javascript_tag "$('#genre_list').select2()" %>
<%= javascript_tag "$('#movie_stars').select2()" %>
<%= javascript_tag "$('#movie_writers').select2()" %>
<%= javascript_tag "$('#movie_directors').select2()" %>

app/views/person/show.html.erb
<a href="<%= movies_path() %>"><- Back to movies</a>

<h1><%= @person.first_name + ' ' + @person.last_name %> </h1>


<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" id="star-tab" data-toggle="tab" href="#star" aria-controls="star" aria-selected="true">Star</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="director-tab" data-toggle="tab" href="#director" aria-controls="director" aria-selected="false">Director</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="writer-tab" data-toggle="tab" href="#writer" aria-controls="writer" aria-selected="false">Writer</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="stats-tab" data-toggle="tab" href="#stats" aria-controls="stats" aria-selected="false">Stats</a>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="star" role="tabpanel" aria-labelledby="star-tab">
    <br><br>
    <% for m in @star %>
      <div class="card mt-2">
        <div class="card-body">
          <h5 class="card-title"><%= m.title %></h5>
          <h6 class="card-subtitle text-muted">
            <span title="runtime">
              <i class="far fa-clock"></i> <%= m.runtime.to_s + "'" %>
            </span>
            &nbsp;
            <span title="avg rating">
              <% if m.ratings.empty? %>
                <i class="far fa-meh-blank"></i> -
              <% elsif m.ratings.average(:score) < 3 %>
                 <i class="far fa-tired"></i> <%= m.ratings.average(:score) %>
              <% elsif m.ratings.average(:score) < 5 %>
                 <i class="far fa-frown"></i> <%= m.ratings.average(:score) %>
              <% elsif m.ratings.average(:score) < 7 %>
                 <i class="far fa-smile"></i> <%= m.ratings.average(:score) %>
              <% elsif m.ratings.average(:score) < 9 %>
                 <i class="far fa-grin"></i> <%= m.ratings.average(:score) %>
              <% else %>
                 <i class="far fa-grin-stars"></i> <%= m.ratings.average(:score) %>
              <% end %>
            </span>
          </h6>

          <p><%= m.description %></p>
          <p>
            <% if m.directors.length >1 %>
              Directors:
            <% else %>
              Director:
            <% end %>
            <% for d in m.directors %>
              <a href="<%= person_path(d.person.id) %>"><%= d.person.first_name + ' ' + d.person.last_name %></a>
            <% end %>
          </p>
          <p>
            <% if m.writers.length >1 %>
              Writers:
            <% else %>
              Writer:
            <% end %>
            <% for w in m.writers %>
              <a href="<%= person_path(w.person.id) %>"><%= w.person.first_name + ' ' + w.person.last_name %></a>
            <% end %>
          </p>
          <p>
            <% if m.stars.length >1 %>
              Stars:
            <% else %>
              Star:
            <% end %>
            <% for s in m.stars %>
              <a href="<%= person_path(s.person.id) %>"><%= s.person.first_name + ' ' + s.person.last_name %></a>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>

  </div>
  <div class="tab-pane fade" id="director" role="tabpanel" aria-labelledby="director-tab">
    <br><br>
    <% for m in @director %>
      <div class="card mt-1">
        <div class="card-body">
          <h5 class="card-title"><%= m.title %></h5>
          <h6 class="card-subtitle text-muted">
            <span title="runtime">
              <i class="far fa-clock"></i> <%= m.runtime.to_s + "'" %>
            </span>
            &nbsp;
            <span title="avg rating">
              <% if m.ratings.empty? %>
                <i class="far fa-meh-blank"></i> -
              <% elsif m.ratings.average(:score) < 3 %>
                 <i class="far fa-tired"></i> <%= m.ratings.average(:score) %>
              <% elsif m.ratings.average(:score) < 5 %>
                 <i class="far fa-frown"></i> <%= m.ratings.average(:score) %>
              <% elsif m.ratings.average(:score) < 7 %>
                 <i class="far fa-smile"></i> <%= m.ratings.average(:score) %>
              <% elsif m.ratings.average(:score) < 9 %>
                 <i class="far fa-grin"></i> <%= m.ratings.average(:score) %>
              <% else %>
                 <i class="far fa-grin-stars"></i> <%= m.ratings.average(:score) %>
              <% end %>
            </span>
          </h6>

          <p><%= m.description %></p>
          <p>
            <% if m.directors.length >1 %>
              Directors:
            <% else %>
              Director:
            <% end %>
            <% for d in m.directors %>
              <a href="<%= person_path(d.person.id) %>"><%= d.person.first_name + ' ' + d.person.last_name %></a>
            <% end %>
          </p>
          <p>
            <% if m.writers.length >1 %>
              Writers:
            <% else %>
              Writer:
            <% end %>
            <% for w in m.writers %>
              <a href="<%= person_path(w.person.id) %>"><%= w.person.first_name + ' ' + w.person.last_name %></a>
            <% end %>
          </p>
          <p>
            <% if m.stars.length >1 %>
              Stars:
            <% else %>
              Star:
            <% end %>
            <% for s in m.stars %>
              <a href="<%= person_path(s.person.id) %>"><%= s.person.first_name + ' ' + s.person.last_name %></a>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="tab-pane fade" id="writer" role="tabpanel" aria-labelledby="writer-tab">
       <br><br>
    <% for m in @writer %>
      <div class="card mt-2">
        <div class="card-body">
          <h5 class="card-title"><%= m.title %></h5>
          <h6 class="card-subtitle text-muted">
            <span title="runtime">
              <i class="far fa-clock"></i> <%= m.runtime.to_s + "'" %>
            </span>
            &nbsp;
            <span title="avg rating">
              <% if m.ratings.empty? %>
                <i class="far fa-meh-blank"></i> -
              <% elsif m.ratings.average(:score) < 3 %>
                 <i class="far fa-tired"></i> <%= m.ratings.average(:score) %>
              <% elsif m.ratings.average(:score) < 5 %>
                 <i class="far fa-frown"></i> <%= m.ratings.average(:score) %>
              <% elsif m.ratings.average(:score) < 7 %>
                 <i class="far fa-smile"></i> <%= m.ratings.average(:score) %>
              <% elsif m.ratings.average(:score) < 9 %>
                 <i class="far fa-grin"></i> <%= m.ratings.average(:score) %>
              <% else %>
                 <i class="far fa-grin-stars"></i> <%= m.ratings.average(:score) %>
              <% end %>
            </span>
          </h6>

          <p><%= m.description %></p>
          <p>
            <% if m.directors.length >1 %>
              Directors:
            <% else %>
              Director:
            <% end %>
            <% for d in m.directors %>
              <a href="<%= person_path(d.person.id) %>"><%= d.person.first_name + ' ' + d.person.last_name %></a>
            <% end %>
          </p>
          <p>
            <% if m.writers.length >1 %>
              Writers:
            <% else %>
              Writer:
            <% end %>
            <% for w in m.writers %>
              <a href="<%= person_path(w.person.id) %>"><%= w.person.first_name + ' ' + w.person.last_name %></a>
            <% end %>
          </p>
          <p>
            <% if m.stars.length >1 %>
              Stars:
            <% else %>
              Star:
            <% end %>
            <% for s in m.stars %>
              <a href="<%= person_path(s.person.id) %>"><%= s.person.first_name + ' ' + s.person.last_name %></a>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="tab-pane fade" id="stats" role="tabpanel" aria-labelledby="stats-tab">
    <div class="card" style="width: 450px;">
      <div class="card-body container">
        <div class="row">
          <p class="col">Movies starred:</p>
          <p class="col"><%= @star.count %></p>
        </div>
        <div class="row">
          <p class="col">Movies written:</p>
          <p class="col"><%= @writer.count %></p>
        </div>
        <div class="row">
          <p class="col">Movies directed:</p>
          <p class="col"><%= @director.count %></p>
        </div>
        <div class="row">
          <p class="col">Total movies participated::</p>
          <p class="col"><%= @director.count + @writer.count + @star.count %></p>
        </div>
        <div class="row">
          <p class="col">Avg rating of movies starred:</p>
          <p class="col"><%= @star.map{|movie| movie.ratings.average(:score)}.sum %></p>
        </div>
        <div class="row">
          <p class="col">Avg rating of movies directed:</p>
          <p class="col"><%= @director.map{|movie| movie.ratings.average(:score)}.sum %></p>
        </div>
        <div class="row">
          <p class="col">Avg rating of movies written:</p>
          <p class="col"><%= @writer.map{|movie| movie.ratings.average(:score)}.sum %></p>
        </div>
         <div class="row">
          <p class="col">Avg rating of total movies:</p>
          <p class="col"><%= (@writer.map{|movie| movie.ratings.average(:score)}.sum + @director.map{|movie| movie.ratings.average(:score)}.sum + @star.map{|movie| movie.ratings.average(:score)}.sum) / 3 %></p>
        </div>
      </div>
    </div>
  </div>
</div>